apiVersion: apps/v1
kind: Deployment
metadata:
  name: medishieldguard-deployment
  namespace: blufountain-insurance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medishieldguard
  template:
    metadata:
      labels:
        app: medishieldguard
    spec:
      containers:
      - name: medishieldguard-container
        image: kaributechsworkflow/medishieldguard:a2948a2de9283a4eb101fc53863fccc4675b5007
        ports:
        - containerPort: 80
