apiVersion: apps/v1
kind: Deployment
metadata:
  name: medishieldguard-deployment
  namespace: blufountain-insurance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medishieldguard
  template:
    metadata:
      labels:
        app: medishieldguard
    spec:
      containers:
      - name: medishieldguard-container
        image: kaributechsworkflow/medishieldguard:d9a3f920e50101ee0a6193cb992783a69bc04352
        ports:
        - containerPort: 80
