apiVersion: apps/v1
kind: Deployment
metadata:
  name: medishieldguard-deployment
  namespace: blufountain-insurance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medishieldguard
  template:
    metadata:
      labels:
        app: medishieldguard
    spec:
      containers:
      - name: medishieldguard-container
        image: kaributechsworkflow/medishieldguard:6a5a0aab82401ba32b836a5af2ba577a98bf14eb
        ports:
        - containerPort: 80
