apiVersion: apps/v1
kind: Deployment
metadata:
  name: medishieldguard-deployment
  namespace: blufountain-insurance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medishieldguard
  template:
    metadata:
      labels:
        app: medishieldguard
        appVersion: '6b90deb2b352388ab248602589acc4527cd9fbe3'
    spec:
      containers:
      - name: medishieldguard-container
        image: kaributechsworkflow/medishieldguard:6b90deb2b352388ab248602589acc4527cd9fbe3
        ports:
        - containerPort: 80
